package br.com.EscolaVNW.Courses;

public enum Curso {

	ANALISE_E_DESENVOLVIMENTO_DE_SISTEMAS,
	CIENCIA_DA_COMPUTACAO,
	ENGENHARIA_DA_COMPUTACAO,
	JOGOS_DIGITAIS,
	REDES,
	SEGURANCA_DA_INFORMACAO,
	ANALISE_DE_DADOS,
	DESENVOLVIMENTO_WEB,
	ADMINISTRACAO_DE_REDES,
	ARQUITETURA_DE_SOFTWARE,
	GERENCIAMENTO_DE_PROJETOS_DE_TI,
	COMPUTACAO_EM_NUVEM,
	INTELIGENCIA_ARTIFICIAL,
	BIG_DATA_E_ANALYTICS,
	INTERNET_DAS_COISAS,
	PROGRAMACAO_MOBILE,
	ENGENHARIA_DE_SOFTWARE
}
